import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import {SliderData} from '../components/SliderData';

export default function Home() {

  return (
    <div>
    
    <Head>
    <title>Photography Template</title>
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='favicon.ico' />
    </Head>
    <Hero heading='Photography Template' message='Photography Portfolio Template.' />
    <Slider slides{SliderData} />
    </div>
  );
  
}